image: docker:latest

services:
  - docker:dind

stages:
  - smoketest

# cache:
#   paths:
#     - .smoketest/repository

checkLogin:
  image: 
    name: smktesting/smoke-master:latest
    entrypoint: [""]
  cache: {}
  stage: smoketest
  script: 
    - echo "TEST"
  # [
  #       'create-smktest',
  #       '--project-name=test',
  #       '--environment=develop',
  #       '--context=kubernetes',
  #       '--namespace=NAMESPACE',
  #       '--mode-auto=true',
  #       '--assert-curl=curl www.google.com',
  #     ]
  only:
    - master

