image: docker:latest

services:
  - docker:dind


stages:
  - test
  - package
  - smoke-curl
  - kubernetes

variables:
  KUBECONFIG: /etc/deploy/config
  PROJECT_NAME: smoke-master
  SMKTEST_PROJECT_NAME: 'SmokeMaster'
  SMKTEST_ENVIRONMENT: 'master'
  SMKTEST_NAMESPACE: 'edutelling-develop'
  SMKTEST_MODE_AUTO: 'true'

# Template for use kubernetes
.smoke-test-kubernetes: &smoke-test-kubernetes
  image: registry.gitlab.com/phdactivities/smoke-master:master
  stage: kubernetes
  before_script:
    # Create cluster remote configuration file. 
    - echo $KUBERNETES_TOKEN | base64 -d > /etc/deploy/config
  variables:
    SMKTEST_CONTEXT: 'kubernetes'

# Template for use Curl smoke test
.smoke-test-curl: &smoke-test-curl
  image: registry.gitlab.com/phdactivities/smoke-master:master
  stage: smoke-curl
  variables:
    SMKTEST_CONTEXT: 'remote-server'

docker-build:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.19.0
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context . --dockerfile Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --cache
  cache: {}
  only:
    - master

pass:
  image: registry.gitlab.com/phdactivities/smoke-master:master
  stage: test
  script:
    - exit 0
  only:
    - master

fail:
  image: registry.gitlab.com/phdactivities/smoke-master:master
  stage: test
  script:
    - exit 1
  only:
    - master

curlGoogle:
  <<: *smoke-test-curl
  script:
    - create-smktest --assert-curl="curl www.google.com"
    - create-smktest --assert-curl="curl www.google.com232332"
    - npm run passTest
  only:
    - master

checkLogin:
  <<: *smoke-test-curl
  variables:
    SMKTEST_ASSERT_CURL: 'curl -X POST "https://edutelling-api-develop.openshift.techgap.it/api/v1/auth/authentication" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"email\": \"formazione@edutelling.it\", \"password\": \"Passw0rd\", \"stayLogged\": false }"'
  script:
    - create-smktest --project-name="SmokeMaster"
  only:
    - master

# Example how connect one remote cluster.
remoteAccess:
  <<: *smoke-test-curl
  script:
    # Create cluster remote configuration file. 
    - echo $KUBERNETES_TOKEN | base64 -d > /etc/deploy/config
    - kubectl get pods --namespace=edutelling-develop
  only:
    - master

# Example how connect one remote cluster
podsActive:
  <<: *smoke-test-kubernetes
  script:
    - create-smktest --check-if-all-pods-are-active=true
  only:
    - master

# Example how connect one remote cluster
ingressPods:
  <<: *smoke-test-kubernetes
  script:
    - create-smktest --check-ingress=true
  only:
    - master

# Example how connect one remote cluster
conditionsCluster:
  <<: *smoke-test-kubernetes
  script:
    - create-smktest --check-conditions=true
  only:
    - master

logsPods:
  <<: *smoke-test-kubernetes
  script:
    - create-smktest --check-pods-logs=true
  only:
    - master

   