image: docker:latest

services:
  - docker:dind


stages:
  - package
  - smoketest
  - kubernetes


variables:
  KUBECONFIG: /etc/deploy/config
  PROJECT_NAME: smoke-master

docker-build:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.19.0
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context . --dockerfile Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --cache
  cache: {}
  only:
    - master


curlGoogle:
  image: 
    name: registry.gitlab.com/phdactivities/smoke-master:master
    entrypoint: [""]
  cache: {}
  stage: smoketest
  script:
    - npm run test
    - 'create-smktest --project-name=test --environment=develop --context=kubernetes --namespace=NAMESPACE --mode-auto=true --assert-curl="curl www.google.com"'
    - 'create-smktest --project-name=test --environment=develop --context=kubernetes --namespace=NAMESPACE --mode-auto=true --assert-curl="curl www.google.com232332"'
  only:
    - master



checkLogin:
  image: 
    name: registry.gitlab.com/phdactivities/smoke-master:master
    entrypoint: [""]
  cache: {}
  stage: smoketest
  variables:
    SMKTEST_ASSERT_CURL: 'curl -X POST "https://edutelling-api-develop.openshift.techgap.it/api/v1/auth/authentication" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"email\": \"formazione@edutelling.it\", \"password\": \"Passw0rd\", \"stayLogged\": false }"'
    SMKTEST_PROJECT_NAME: 'SmokeMaster'
    SMKTEST_ENVIRONMENT: 'master'
  script:
    - 'create-smktest --project-name=test --context=kubernetes'
  only:
    - master

# Example how connect one remote cluster.
remoteAccess:
  image: 
    name: registry.gitlab.com/phdactivities/smoke-master:master
  stage: kubernetes
  script:
    # Create cluster remote configuration file. 
    - echo $KUBERNETES_TOKEN | base64 -d > /etc/deploy/config
    - kubectl get pods --namespace=edutelling-develop
  only:
    - master

# Example how connect one remote cluster
podsActive:
  image: 
    name: registry.gitlab.com/phdactivities/smoke-master:master
  stage: kubernetes
  variables:
    SMKTEST_PROJECT_NAME: 'SmokeMaster'
    SMKTEST_ENVIRONMENT: 'master'  
    SMKTEST_CONTEXT: 'kubernetes'
    SMKTEST_NAMESPACE: 'edutelling-develop'
    SMKTEST_MODE_AUTO: 'true'
  script:
    # Create cluster remote configuration file. 
    - echo $KUBERNETES_TOKEN | base64 -d > /etc/deploy/config
    - create-smktest --check-if-all-pods-are-active=true
  only:
    - master

# Example how connect one remote cluster
ingressPods:
  image: 
    name: registry.gitlab.com/phdactivities/smoke-master:master
  stage: kubernetes
  variables:
    SMKTEST_PROJECT_NAME: 'SmokeMaster'
    SMKTEST_ENVIRONMENT: 'master'  
    SMKTEST_CONTEXT: 'kubernetes'
    SMKTEST_NAMESPACE: 'edutelling-develop'
    SMKTEST_MODE_AUTO: 'true'
  script:
    # Create cluster remote configuration file. 
    - echo $KUBERNETES_TOKEN | base64 -d > /etc/deploy/config
    - create-smktest --check-ingress=true
  only:
    - master

# Example how connect one remote cluster
conditionsCluster:
  image: 
    name: registry.gitlab.com/phdactivities/smoke-master:master
  stage: kubernetes
  variables:
    SMKTEST_PROJECT_NAME: 'SmokeMaster'
    SMKTEST_ENVIRONMENT: 'master'  
    SMKTEST_CONTEXT: 'kubernetes'
    SMKTEST_NAMESPACE: 'edutelling-develop'
    SMKTEST_MODE_AUTO: 'true'
  script:
    # Create cluster remote configuration file. 
    - echo $KUBERNETES_TOKEN | base64 -d > /etc/deploy/config
    - create-smktest --check-conditions=true
  only:
    - master

logsPods:
  image: 
    name: registry.gitlab.com/phdactivities/smoke-master:master
  stage: kubernetes
  variables:
    SMKTEST_PROJECT_NAME: 'SmokeMaster'
    SMKTEST_ENVIRONMENT: 'master'  
    SMKTEST_CONTEXT: 'kubernetes'
    SMKTEST_NAMESPACE: 'edutelling-develop'
    SMKTEST_MODE_AUTO: 'true'
  script:
    # Create cluster remote configuration file. 
    - echo $KUBERNETES_TOKEN | base64 -d > /etc/deploy/config
    - create-smktest --check-pods-logs=true
  only:
    - master

   