image: docker:latest

services:
  - docker:dind

stages:
  - smoketest

cache:
  paths:
    - .m2/repository

checkLogin:
  stage: smoketest
  # script:  pwd
  step_script: pwd
  # [
  #       'create-smktest',
  #       '--project-name=test',
  #       '--environment=develop',
  #       '--context=kubernetes',
  #       '--namespace=NAMESPACE',
  #       '--mode-auto=true',
  #       '--assert-curl=curl www.google.com',
  #     ]
  image: smktesting/smoke-master:latest
  only:
    - master

