image: docker:latest

services:
  - docker:dind

stages:
  - package
  - smoke-curl
  - kubernetes
  - docker-hub

variables:
  CI_VERSION: "1.0.${CI_JOB_ID}"
  KUBECONFIG: /etc/deploy/config
  PROJECT_NAME: smoke-master
  SMKTEST_PROJECT_NAME: 'SmokeMaster'
  SMKTEST_ENVIRONMENT: 'master'
  SMKTEST_NAMESPACE: 'edutelling-develop'
  SMKTEST_MODE_AUTO: 'true'
  SMOKE_COLLECTOR: $SMOKE_COLLECTOR

# Template for use kubernetes.
.smoke-test-kubernetes: &smoke-test-kubernetes
  image: registry.gitlab.com/phdactivities/smoke-master:master
  stage: kubernetes
  before_script:
    # Create cluster remote configuration file. 
    - echo $KUBERNETES_TOKEN | base64 -d > /etc/deploy/config
  variables:
    SMKTEST_CONTEXT: 'kubernetes'

# Template for use Curl smoke test.
.smoke-test-curl: &smoke-test-curl
  image: registry.gitlab.com/phdactivities/smoke-master:master
  stage: smoke-curl
  variables:
    SMKTEST_CONTEXT: 'remote-server'

docker-build:
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.19.0
    entrypoint: [""]
  stage: package  
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context . --dockerfile Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --cache
  only:
    - master

curlGoogle:
  <<: *smoke-test-curl
  variables:
    SMKTEST_BREAK_HOW_WARNING: true
  script:
    - create-smktest --assert-curl="curl www.google.com"
    - create-smktest --assert-curl="curl www.google.comasdad"
  only:
    - master

checkLogin:
  <<: *smoke-test-curl
  variables:
    SMKTEST_ASSERT_CURL: 'curl -X POST "https://edutelling-api-develop.openshift.techgap.it/api/v1/auth/authentication" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"email\": \"formazione@edutelling.it\", \"password\": \"Passw0rd\", \"stayLogged\": false }"'
  script:
    - create-smktest --context=remote-server
  only:
    - master

# Example how connect one remote cluster.
remoteAccess:
  <<: *smoke-test-curl
  script:
    # Create cluster remote configuration file. 
    - echo $KUBERNETES_TOKEN | base64 -d > /etc/deploy/config
    - kubectl get pods --namespace=edutelling-develop
  only:
    - master

# Example how connect one remote cluster
podsActive:
  <<: *smoke-test-kubernetes
  script:
    - create-smktest --check-if-all-pods-are-active=true
  only:
    - master

# Example how connect one remote cluster
ingressPods:
  <<: *smoke-test-kubernetes
  script:
    - echo $SMOKE_COLLECTOR
    - create-smktest --check-ingress=true
  only:
    - master

# Example how connect one remote cluster
conditionsCluster:
  <<: *smoke-test-kubernetes
  script:
    - create-smktest --check-conditions=true
  only:
    - master

logsPods:
  <<: *smoke-test-kubernetes
  script:
    - create-smktest --check-pods-logs=true
  only:
    - master


pushDockerHub:
  image: docker:latest
  stage: docker-hub
  services:
    - docker:dind   
  before_script:
    - docker login --username $DOCKER_USER -p $DOCKER_TOKEN
  script:
    - docker build --pull -t "smktesting/smoke-master:$CI_VERSION" .
    - docker push "smktesting/smoke-master:$CI_VERSION"
    - docker build --pull -t "smktesting/smoke-master:latest" .
    - docker push "smktesting/smoke-master:latest"    
  only:
    - master